version: '3.8'

services:
#  postgres:
#    image: postgres
#    container_name: postgres
#    hostname: postgres
#    environment:
#      POSTGRES_DB: "postgres"
#      POSTGRES_USER: "admin"
#      POSTGRES_PASSWORD: "admin"
#    #command: postgres -p 5432
##    volumes:
##      - ./tickets/deploy/init.sql:/docker-entrypoint-initdb.d/init.sql
##      - pg_data:/var/lib/postgresql
#    networks:
#      - net
#    ports:
#      - "5432:5432"
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
#      interval: 10s
#      retries: 5
#      start_period: 30s
#      timeout: 10s


#  consul:
#    image: consul:1.15.4
#    container_name: consul
#    networks:
#      - net
#    ports:
#      - "8500:8500"


  city-management-service:
    #build: ./CityManagementService
    build: ./city
    container_name: city-management-service
    hostname: city-management-service
    ports:
      - "8080:8080" # Перенаправление HTTP
      - "8181:8181" # Перенаправление HTTPS
      - "4848:4848" # Административная консоль
      - "8500:8500" # consul
#    depends_on:
#      - consul
    networks:
      - net
#
#  route-calculation-service:
#    build: ./RouteCalculationService
#    container_name: route-calculation-service
#    ports:
#      - "8081:8080" # Перенаправление HTTP
#      - "8182:8181" # Перенаправление HTTPS
#      - "4849:4848" # Административная консоль
#    depends_on:
#      - consul
#    networks:
#      - net


networks:
  net: